# Generated by Django 5.2.1 on 2025-06-05 20:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.AddField(
            model_name='user',
            name='following_users',
            field=models.ManyToManyField(related_name='followers_users', through='accounts.Follow', through_fields=('follower', 'following'), to=settings.AUTH_USER_MODEL),
        ),
    ]
